version: ''
services:
  app:
    image: node:17.7.1
    ports:
      - 3000:80
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./app
    working_dir: ./app
    command: npm run start
    depends_on:
      - db
    restart: on-failure
  
  db:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./datas:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: on-failure
    ports:
      - 3030:80
    environment:
      - PMA_ARBITRARY=1